- name: Update cache
  apt: update_cache=yes

- name: Install curl
  apt: name="{{ item }}" state=present
  with_items:
    - gnupg-curl
    - curl

- name: Update key for mongodb
  apt_key: keyserver=keyserver.ubuntu.com id=0C49F3730359A14518585931BC711F9BA15703C6

- name: Create mongo source list
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present

- name: Install mongodb, rabbitmq and postgresql
  apt: name="{{ item }}" state=present
  with_items:
    - mongodb-org
    - rabbitmq-server
    - postgresql

- name: Set mongod INIT status and start
  service: name=mongod state=started enabled=yes

- name: Download installation script
  get_url: url=https://packagecloud.io/install/repositories/StackStorm/stable/script.deb.sh dest=/tmp/st2_installer.sh mode=0755

- name: Run st2-installer script
  shell: /tmp/st2_installer.sh
  args:
    executable: bash

- name: Install st2 and st2-mistral
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - st2
    - st2mistral
