- name: Update cache
  apt: update_cache=yes

- name: Install curl
  apt: name="{{ item }}" state=present
  with_items:
    - gnupg-curl
    - curl

- name: Update key for mongodb
  apt_key: keyserver=keyserver.ubuntu.com id=0C49F3730359A14518585931BC711F9BA15703C6

- name: Create mongo source list
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    state: present

- name: Install mongodb, rabbitmq and postgresql
  apt: name="{{ item }}" state=present
  with_items:
    - mongodb-org
    - rabbitmq-server
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Set mongod INIT status and start
  service: name=mongod state=started enabled=yes

- name: Download installation script
  get_url: url=https://packagecloud.io/install/repositories/StackStorm/stable/script.deb.sh dest=/tmp/st2_installer.sh mode=0755

- name: Run st2-installer script
  shell: /tmp/st2_installer.sh
  args:
    executable: bash

- name: Install st2 and st2-mistral
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - st2
    - st2mistral

- name: Create postgres user for mistral
  postgresql_user:
    state: present
    name: mistral
    password: StackStorm
    encrypted: yes
    role_attr_flags: CREATEDB,LOGIN
  become_user: postgres

- name: Create postgres db for mistral
  postgresql_db: name=mistral owner=mistral state=present
  become_user: postgres

- name: Create mistral tables
  command: /opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf upgrade head
  become_user: mistral

- name: Populate mistral tables
  command: /opt/stackstorm/mistral/bin/mistral-db-manage --config-file /etc/mistral/mistral.conf populate
  become_user: mistral

- name: Add system user
  user:
    name: stanley
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/stanley_rsa

- name: Copy configuration file
  template:
    src: ../template/st2.conf.j2
    dest: /etc/st2/st2.conf
    backup: yes
